### ISSUE TITLE
Resolve the labels in the entities jump table

### ISSUE THREAD

**Issue by kemenaran** [zladx/LADX-Disassembly#80]
There a huge jump table, jumping to the code for handling every type of entity. It should be easy to track the code it jumps to.

https://github.com/zladx/LADX-Disassembly/blob/master/src/code/entities/_handlers_table.asm#L13

**TODO**

- [x] Commit the disassembly of all banks containing entities code
- [x] Move the code to its own `code/entities` directory
- [x] Make a list of all entities types (in https://github.com/zladx/LADX-Disassembly/blob/master/src/constants/entities.asm)
- [ ] Convert raw addresses into labels

**Comment by kemenaran** [comment]
Work slowly started in #86. Still lot of pointers to label manually though :)

**Comment by kemenaran** [comment]
#95 had a list of all entities. It should make it much easier to label the entity handlers.

**Comment by kemenaran** [comment]
Code for known entities is now separated in their own files.

Still quite a lot of labeling work to do though.
